// packages/design-system/src/components/Separator.vue
<script setup lang="ts">
import { Separator as RekaSeparator } from 'reka-ui'

defineOptions({ name: 'FlSeparator' })

withDefaults(
  defineProps<{
    orientation?: 'horizontal' | 'vertical'
  }>(),
  {
    orientation: 'horizontal'
  }
)
</script>

<template>
  <RekaSeparator
    data-slot="separator"
    :orientation="orientation"
    :class="[
      'shrink-0 bg-[var(--fl-color-border)]',
      orientation === 'horizontal' && 'h-px w-full',
      orientation === 'vertical' && 'h-full w-px'
    ]"
  />
</template>

// apps/frontend/src/components/ui/separator.tsx
import { Separator as SeparatorPrimitive } from '@base-ui/react/separator'

import { cn } from '@/lib/utils'

function Separator({ className, orientation = 'horizontal', ...props }: SeparatorPrimitive.Props) {
  return (
    <SeparatorPrimitive
      data-slot='separator'
      orientation={orientation}
      className={cn(
        'shrink-0 bg-border data-horizontal:h-px data-horizontal:w-full data-vertical:w-px data-vertical:self-stretch',
        className
      )}
      {...props}
    />
  )
}

export { Separator }
